CREATE TABLE IF NOT EXISTS Msg(id integer , uname VARCHAR(255) ,email VARCHAR(255), text VARCHAR(255), ip VARCHAR(255), browser VARCHAR(255));
DELETE FROM Msg;
INSERT INTO Msg (uname, email, text, ip, browser ) VALUES('John', '1@gmail.com', 'hello world', '192.168.1.10', 'Chrome');
INSERT INTO Msg (uname, email, text, ip, browser ) VALUES('Max', '2@gmail.com', 'world is mine', '192.168.1.11', 'Mozilla');
INSERT INTO Msg (uname, email, text, ip, browser ) VALUES('Oleg', '3@gmail.com', 'hello Ben', '192.168.1.13', 'IE');
INSERT INTO Msg (uname, email, text, ip, browser ) VALUES('Anna', '4@gmail.com', 'hello earth', '192.168.1.14', 'Chrome');
INSERT INTO Msg (uname, email, text, ip, browser ) VALUES('Ben', '5@gmail.com', 'earth world', '192.168.1.16', 'Opera');
INSERT INTO Msg (uname, email, text, ip, browser ) VALUES('Chen', '11@gmail.com', 'earth 1', '192.168.1.12', 'Mozilla');
INSERT INTO Msg (uname, email, text, ip, browser ) VALUES('Woo', '12@gmail.com', '2 world', '192.168.1.21', 'Chrome');
INSERT INTO Msg (uname, email, text, ip, browser ) VALUES('Keysey', '13@gmail.com', 'hello 3', '192.168.1.43', 'Opera');
INSERT INTO Msg (uname, email, text, ip, browser ) VALUES('Brad', '14@gmail.com', '4 world', '192.168.1.56', 'IE');
INSERT INTO Msg (uname, email, text, ip, browser ) VALUES('Eugene', '15@gmail.com', 'hello 5', '192.168.1.66', 'Chrome');
INSERT INTO Msg (uname, email, text, ip, browser ) VALUES('Egor', '21@gmail.com', '6 world', '192.168.1.37', 'Mozilla');
INSERT INTO Msg (uname, email, text, ip, browser ) VALUES('Pasha', '22@gmail.com', 'hello 7', '192.168.1.76', 'Chrome');
INSERT INTO Msg (uname, email, text, ip, browser ) VALUES('Dana', '23@gmail.com', '8 world', '192.168.1.47', 'Mozilla');
INSERT INTO Msg (uname, email, text, ip, browser ) VALUES('Nata', '24@gmail.com', 'hello 9', '192.168.1.61', 'IE');
INSERT INTO Msg (uname, email, text, ip, browser ) VALUES('Yana', '25@gmail.com', '10 world', '192.168.1.55', 'Chrome');
INSERT INTO Msg (uname, email, text, ip, browser ) VALUES('Katya', '31@gmail.com', 'hello 11', '192.168.1.58', 'Mozilla');
INSERT INTO Msg (uname, email, text, ip, browser ) VALUES('Olya', '32@gmail.com', '12 world', '192.168.1.91', 'Chrome');
INSERT INTO Msg (uname, email, text, ip, browser ) VALUES('Pit', '33@gmail.com', 'hello 15', '192.168.1.100', 'IE');
